### PR TITLE
branch support

### LINKED ISSUE #2: Branch support
I have noticed in the backlog branches support but I wanted to create an issue for further references. We may contribute if we could find time for it.

### PR DESCRIPTION
**Pull request by cemo**
Resolves #2

### CODE REVIEW

**Comment by cemo** [comment]
I will be glad that if you will give a try before merging.

**Comment by s1ntaxe770r** [comment]
Hey @cemo, I gave your feature a try, it works well. Thank you!

**Comment by cemo** [comment]
Can you cut a release please?

**Comment by s1ntaxe770r** [comment]
done!

**Pull request merged**
